---
# vars file for server-sing-box
singbox_path: /usr/local/bin/singbox
singbox_core_name: linux-amd64
# singbox_core_name: {{ {"x86_64": "linux-amd64", "aarch64": "android-arm64", "armv7l": "android-armv7"}[ansible_architecture] | default("") }}
singbox_core_url: 'https://github.com/SagerNet/sing-box/releases/download/v{{ singbox_core_ver.stdout }}/sing-box-{{ singbox_core_ver.stdout }}-{{ singbox_core_name }}.tar.gz'
server_ipv4: '{{ ansible_default_ipv4.address }}' 
listen_port: 443
server_name: 'telewebion.com'
