---
# tasks file for server-sing-box
- name: Creating singbox directory if it does not exist
  ansible.builtin.file:
    path: '{{ singbox_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Extracting downloaded singbox
  ansible.builtin.unarchive:
    src: '{{ singbox_core_url }}'
    dest: '{{ singbox_path }}'
    remote_src: yes 
- name: Changing mode singbox file
  ansible.builtin.file:
    path: '{{ singbox_path }}/singbox'
    mode: '0755'
- name: Template for reality.json
  ansible.builtin.template:
    src: reality.json.jinja
    dest: '{{ singbox_path }}/reality.json'
    mode: '0644'
- name: Return key pair to registered var
  ansible.builtin.command: '{{ singbox_path }}/singbox generate reality-keypair'
  register: key_pair
- name: Return UUID to registered var
  ansible.builtin.command: '{{ singbox_path }}/singbox generate uuid'
  register: uuid    
- name: Template for singbox.service
  ansible.builtin.template:
    src: singbox.service.jinja
    dest: '/etc/systemd/system/singbox.service'
    mode: '0644'
- name: Enabling and starting singbox.service
  ansible.builtin.shell: systemctl daemon-reload && systemctl enable --now singbox
- name: Print the server details
  ansible.builtin.debug:
    msg:
    - "Server IP: {{ server_ip }}"
    - "Listen Port: {{ listen_port }}"
    - "Server Name: {{ server_name }}"
    - "Private Key: {{ private_key }}"
    - "Public Key: {{ public_key }}"
    - "Short ID: {{ short_id }}"
    - "UUID: {{ uuid }}"

