---
# tasks file for install-singbox
- name: check ping
  ansible.builtin.ping:
  when: false

- name: Remove old singbox
  import_tasks: remove-singbox.yml
  when: run_unnecessary_task

- name: Upgrade all packages on servers
  import_tasks: upgrade.yml
  when: true

- name: Download singbox
  import_tasks: download-singbox.yml
  when: true

- name: Config singbox
  import_tasks: config-singbox.yml
  when: true

- name: Start service singbox
  import_tasks: service-singbox.yml
  when: true

- name: Generate qrcode
  import_tasks: qrcode-singbox.yml
  when: true
