- name: get service facts
  ansible.builtin.service_facts:
- name: Stop service singbox, if started
  ansible.builtin.systemd:
    name: singbox.service
    state: stopped
    enabled: false
  when: ansible_facts.services["singbox.service"] is defined
- name: stat old_singbox_service
  stat: path=/etc/systemd/system/singbox.service
  register: old_singbox_service_stat
- name: Remove singbox.service file (delete file)
  ansible.builtin.file:
    path: /etc/systemd/system/singbox.service
    state: absent
  when: old_singbox_service_stat.stat.exists
- name: stat old_singbox_dir
  stat: path={{ singbox_parent_path }}/singbox
  register: old_singbox_dir_stat
- name: Remove old singbox's dir before installation
  ansible.builtin.command:
    cmd: rm -r {{ singbox_parent_path }}/singbox
  when: old_singbox_dir_stat.stat.exists
