- name: Update apt repo and cache on all Debian/Ubuntu boxes
  ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all packages on servers
  ansible.builtin.apt: upgrade=dist force_apt_get=yes
- name: Install curl, jq and qrencode
  ansible.builtin.package:
    name:
      - curl
      - jq
      - qrencode
    state: present
