---
- name: Installing sing-box on servers
  hosts: servers
  gather_facts: true
  become: true
  roles:
  - server-sing-box
  tags:
  - servers
- name: Installing sing-box on clients
  hosts: clients
  gather_facts: true
  become: true
  roles:
  - client-sing-box
  tags:
  - clients